# Port
server:
  port: 9050

# Spring Boot settings
security: 
    basic: 
        enabled: false
        
# Spring settings
spring: 
    jmx: 
        enabled: false
    application:
        name: SolicitationDataService
    jackson: 
        serialization-inclusion: non_null

# Database connection settings
databaseConnection:
    driver: com.sybase.jdbc4.jdbc.SybDriver
    url: "jdbc:sybase:Tds:fldevel15.nsf.gov:5000/fldb"
    username: flpupd
    password: k2,OnivH

# Eureka connection    
eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8082/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}