package gov.nsf.research.psm.proposal.transfer.proposals;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed May 04 00:21:05 EDT 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "ProposalService-V1.0", name = "ProposalService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProposalService {

    @WebMethod
    @WebResult(name = "saveProposalFindingResponse", targetNamespace = "ProposalService-V1.0", partName = "saveProposalFindingResponse")
    public SaveProposalFindingResponse saveProposalFinding(
        @WebParam(partName = "saveProposalFindingRequest", name = "saveProposalFindingRequest", targetNamespace = "ProposalService-V1.0")
        SaveProposalFindingRequest saveProposalFindingRequest
    );

    @WebMethod
    @WebResult(name = "getProposalResponse", targetNamespace = "ProposalService-V1.0", partName = "getProposalResponse")
    public GetProposalResponse getProposal(
        @WebParam(partName = "getProposalRequest", name = "getProposalRequest", targetNamespace = "ProposalService-V1.0")
        GetProposalRequest getProposalRequest
    );
}
