package gov.nsf.research.psm.rules.factmodel;

public enum ProposalSection {

	COVER_SHEET,
	PROJECT_SUMMARY,
	PROJECT_DESCRIPTION,
	REFERENCES_CITED,
	BIO_SKETCHES,
	BUDGET,
	BUDGET_JUSTIFICATION,
	CURRENT_PENDING_SUPPORT,
	FACILITIES_EQUIP_OTHER,
	DATA_MGT_PLAN,
	MENTORING_PLAN,
	PROPOSAL_CLASSIFICATION,
	 PROPOSAL_DATA_FORM;
	
}
