server:
  port: 8500

spring:
  application:
    name: TestClient

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:9600/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false